# Prefix
## ߦߍߕߎ߲

In [4]:
# HIDDEN
import pandas as pd
from IPython.display import HTML

# Define headers and values (as lists)
headers = ['name', 'nko', 'pronounciation', 'nko pronouncition']
values = [
    ['tun', 'Connect', '',''],
    ['tunli', '', '',''],
    ['tunni', 'Connection', '',''],    
    ['tunta', 'Connectable', '',''],
    ['tunna', '', '',''],
    ['tunma', 'Connector (person)', '',''],
    ['tunnen', '', '',''],
    ['tuntoh', '', '',''], 
    ['tunra', '', '',''],
    ['tundi', '', '',''],
    ['faa', '', '',''],  
]

# Create the DataFrame with headers and rows of values
df = pd.DataFrame(values, columns=headers)

# Function to color the second row (index 2) in green
def color_row_green(row):
    #print(row)
    return ['background-color: lightgreen'] * len(row) if row.name == 2 else [''] * len(row)

# Apply the row coloring
styled_df = df.style.apply(color_row_green, axis=1)


HTML(df.to_html(escape=False))